# 整个流程的名字
name: Release

# 触发时机，在 main 分支 push 操作触发
on:
  push:
    branches:
      - master

# 默认shell
defaults:
  run:
    shell: bash

# 任务，定义个changelog 的任务
jobs:
  changelog:
    name: changelog pr or Release
    # 这里判断仓库owner是否是我自己，为了避免别人 fork 仓库触发，请自行修改
    if: ${{ github.repository_owner == 'zcy22606' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 设置 pnpm 指定版本为7.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^7.0
        # 设置Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: create release pull request or publish
        id: changesets
        uses: changesets/action@v1
        with: 
          version: pnpm run version
          publish: pnpm exec changeset publish
          commit: '[ci] release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}